server:
  port: ${PORT:8086}
  url: ${SERVER_URL:http://localhost:8086}

spring:
  application:
    name: PIT

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=PIT;encrypt=false;trustServerCertificate=true
    username: sa
    password: TuPasswordFuerte123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
    path: /api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    #docker run -e "ACCEPT_EULA=Y" -e "MSSQL_PID=Developer" -e "SA_PASSWORD=Alexis123!" -p 1433:1433 --name sqlserver-pit -d mcr.microsoft.com/mssql/server:2022-latest